# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c

podfile: Example/Podfile

before_install:
  - brew install swiftlint
  - gem install cocoapods --pre

osx_image:
  - xcode7.3
  - xcode8

matrix:
    include:
        # Swift 2.3
        - os: osx
          osx_image: xcode8
          env:
            - TASK=lintpod
              SWIFT_VERSION=2.3

        # Swift 2.2
        - os: osx
          osx_image: xcode7.3
          env: TASK=lintpod

script:
  - rake ci:$TASK
